In [1]:
%matplotlib inline
from matplotlib import pylab as plt

from geonotebook.wrappers import RasterData

rd = RasterData('/data/kotfic/climate/tasmax_day_BCSD_rcp45_r1i1p1_ACCESS1-0_2100.nc')

cmap = plt.get_cmap('hot_r', 50)

M.set_center(0, 0, 2).then(
    M.add_layer(
        rd[1], colormap=cmap, opacity=0.8, min=201.5, max=327.1,
        vrt_path="vrt/tasmax_day_BCSD_rcp45_r1i1p1_ACCESS1-0_2100.vrt"))

In [3]:
from geonotebook.vis.utils import generate_colormap
import pandas as pd

def highlight(e):
    return "background-color: {}".format(e)

df = pd.DataFrame(generate_colormap(cmap, 201.5, 327.1)).rename(columns={"quantity": "kelvin"})
df['fahrenheit'] = df['kelvin'] * (9 / 5.) - 459.67
df['celsius'] = df['kelvin'] - 273.15

df.style.applymap(highlight)

In [4]:
M.layers.annotation.rectangles[0]

In [5]:
M.layers.annotation.rectangles[0].data.next

In [6]:
M.layers.annotation.rectangles[0].data.next()

(<SimpleLayer('tasmax_day_BCSD_rcp45_r1i1p1_ACCESS1-0_2100')>,
 masked_array(data =
  [[ 299.77642822  299.47000122  299.21322632  299.03503418  298.9602356
    298.97598267  299.1149292   299.16946411  299.11929321  299.19390869
    299.24932861  299.16247559  299.03933716  299.07141113  298.93008423
    298.75518799  298.54379272  298.34439087  298.09320068  297.94256592
    297.70391846  297.269104    296.76992798  296.55636597  296.53317261
    296.27185059  296.06045532  295.8482666   295.94918823  295.82672119]
  [ 299.71112061  299.32241821  299.08981323  298.97906494  298.82171631
    298.80813599  299.00033569  299.13018799  299.16439819  299.3036499
    299.3265686   299.31793213  299.18319702  299.24591064  299.26031494
    299.20046997  298.97662354  298.72634888  298.56948853  298.31378174
    297.85366821  297.09371948  297.03720093  296.49694824  296.55969238
    296.00366211  296.06152344  296.09625244  295.89160156  295.77062988]
  [ 299.6656189   299.28274536  298.91833496  298.92373657  298.83639526
    298.83938599  298.99337769  299.03884888  299.09521484  299.51022339
    299.60742188  299.6739502   299.66781616  299.68612671  299.81344604
    299.69271851  299.47442627  299.18347168  298.90530396  298.59017944
    298.10284424  297.86703491  297.32788086  296.85650635  296.42602539
    295.89901733  296.46340942  296.31362915  296.0256958   295.8928833 ]
  [ 299.69943237  299.15228271  298.78735352  298.93600464  298.89941406
    298.93048096  299.02923584  299.13314819  299.27932739  299.6489563
    299.80258179  299.98373413  300.15881348  300.10897827  300.10934448
    299.90621948  299.75842285  299.39230347  299.14013672  298.88317871
    298.68823242  298.31677246  297.76132202  297.22924805  297.05325317
    296.7512207   296.70629883  296.48495483  296.21307373  296.09585571]
  [ 299.77667236  299.31124878  299.00704956  298.72567749  298.69882202
    298.78683472  298.99307251  299.39068604  299.6366272   299.83267212
    299.94656372  300.17333984  300.51815796  300.41397095  300.26889038
    300.20773315  300.06576538  299.70599365  299.18103027  299.21209717
    299.04241943  298.55227661  298.1595459   297.83261108  297.57189941
    297.34066772  296.83660889  296.77243042  296.38430786  296.15823364]
  [ 299.81756592  299.38278198  298.97070312  298.60388184  298.55151367
    298.54504395  298.93264771  299.55609131  299.90060425  300.11224365
    300.42379761  300.64584351  301.04397583  300.83987427  300.58880615
    300.56533813  300.29992676  299.73171997  299.15612793  299.2354126
    299.21087646  298.96420288  298.7593689   298.40866089  298.09603882
    297.30514526  297.2706604   297.03237915  296.42904663  296.25595093]
  [ 299.90924072  299.57937622  299.26715088  299.00631714  298.75692749
    298.85076904  299.33013916  299.85971069  300.25018311  300.44723511
    300.90585327  301.04632568  301.47918701  301.33929443  301.10153198
    300.82556152  300.49023438  299.93179321  299.35073853  299.58795166
    299.38467407  299.17443848  299.06192017  298.66769409  298.41125488
    298.17883301  297.65127563  296.98092651  296.65988159  296.89990234]
  [ 300.09674072  299.80584717  299.45449829  299.06155396  298.97564697
    299.38900757  299.78182983  300.27706909  300.79248047  301.20346069
    301.49185181  301.63388062  301.95684814  301.7180481   301.4145813
    301.10583496  300.52728271  299.8638916   299.89181519  299.97955322
    299.60769653  299.35842896  299.32116699  298.9994812   298.73123169
    298.33682251  297.84515381  297.56793213  297.48031616  297.12823486]
  [ 300.27822876  299.99200439  299.71694946  299.41027832  299.16122437
    299.63137817  300.20751953  300.77685547  301.34637451  301.65258789
    301.84179688  301.99972534  302.02114868  301.72119141  301.55297852
    301.01568604  299.85244751  299.97741699  300.07836914  299.91110229
    299.76733398  299.58001709  299.4564209   299.16558838  298.96786499
    298.61734009  298.54904175  298.05206299  297.36276245  297.08203125]
  [ 300.42297363  300.17788696  299.96072388  299.74041748  299.40640259
    299.96231079  300.57965088  301.15112305  301.52752686  301.19436646
    302.03518677  302.09396362  302.17669678  301.91714478  301.64529419
    300.15673828  299.72186279  300.11395264  300.07080078  300.00552368
    299.9715271   299.70300293  299.79425049  299.63842773  299.28829956
    299.18789673  298.86471558  297.92584229  297.36859131  297.04888916]
  [ 300.47283936  300.31491089  300.22695923  300.12213135  300.10003662
    300.54577637  301.11364746  301.55175781  301.76852417  301.77905273
    302.07315063  302.28765869  302.26919556  301.96469116  301.12176514
    299.68780518  300.09341431  300.22174072  300.14572144  300.13885498
    300.10272217  299.90209961  300.16763306  300.05984497  299.73757935
    299.43069458  299.18426514  298.29608154  297.72036743  297.5682373 ]
  [ 300.465271    300.39797974  300.4460144   300.60235596  300.76733398
    301.13861084  301.59072876  301.89224243  302.08242798  302.14971924
    302.27859497  302.22119141  302.20617676  301.09780884  299.16201782
    300.31970215  300.48370361  300.45947266  300.37051392  300.16333008
    299.81451416  299.27435303  299.56329346  299.92724609  299.87149048
    299.57818604  299.39538574  298.71228027  297.91772461  298.12738037]
  [ 300.572052    300.5647583   300.71231079  300.978302    301.34051514
    301.68737793  301.96655273  302.03387451  301.82125854  301.45648193
    301.8458252   301.62567139  301.43057251  299.10766602  299.29693604
    300.48001099  300.77322388  300.80209351  300.58206177  299.88394165
    300.02316284  299.85028076  299.77020264  299.62911987  299.99832153
    299.89007568  299.67990112  299.13726807  298.52081299  298.3274231 ]
  [ 300.890625    301.01177979  301.23510742  301.53805542  301.93664551
    302.08279419  302.14782715  302.10913086  301.89761353  301.50689697
    301.19778442  300.68240356  300.70748901  299.14425659  299.09216309
    300.23843384  300.64123535  300.69918823  300.55136108  300.05712891
    299.84225464  299.84619141  299.80145264  299.94235229  300.12460327
    300.08944702  299.75491333  299.56390381  299.08996582  298.65151978]
  [ 301.38668823  301.54898071  301.57824707  301.83911133  302.26431274
    302.44952393  302.46243286  302.39437866  302.33682251  302.02774048
    301.38818359  300.51730347  300.88320923  299.11682129  298.97338867
    300.48257446  300.79171753  300.3961792   300.31903076  300.23080444
    300.39138794  300.4208374   300.24664307  300.37966919  300.40496826
    300.22177124  300.22918701  299.7421875   299.6350708   299.12811279]
  [ 301.80407715  301.96264648  302.11834717  302.3480835   302.60513306
    302.78823853  302.79547119  302.78921509  302.78225708  302.37774658
    301.70394897  301.61685181  301.17929077  299.6111145   300.00747681
    301.06988525  301.21777344  301.48919678  300.95504761  300.31643677
    300.55383301  300.60064697  300.44116211  300.51821899  300.67636108
    300.50793457  300.44186401  300.32739258  300.18682861  299.69714355]
  [ 302.09274292  302.20681763  302.42428589  302.68612671  302.9173584
    303.08197021  303.13314819  303.14587402  303.05026245  302.81143188
    302.51174927  302.4571228   302.33703613  301.33065796  301.40158081
    302.24084473  302.50286865  302.10656738  301.38128662  300.63858032
    300.58798218  300.78781128  300.85406494  300.58926392  300.56402588
    300.97409058  300.68188477  300.81640625  300.61523438  300.31130981]
  [ 302.37960815  302.50967407  302.49685669  302.77227783  303.20281982
    303.32937622  303.3454895   303.32333374  303.24069214  303.07202148
    302.93444824  302.91952515  302.53149414  301.79446411  301.92858887
    302.45101929  302.61227417  302.18197632  301.81848145  300.91137695
    301.03561401  301.15362549  301.15509033  301.09347534  301.19485474
    301.32675171  301.31991577  301.26177979  301.05209351  300.83157349]
  [ 302.38357544  302.49276733  302.47650146  303.07824707  303.36135864
    303.44122314  303.41519165  303.33706665  303.22317505  303.06112671
    302.99395752  302.98751831  302.70806885  302.59640503  302.63552856
    302.94256592  302.67919922  302.32672119  302.10610962  301.61550903
    301.47241211  301.5652771   301.5501709   301.46774292  301.70465088
    301.81689453  301.87805176  301.83984375  301.51516724  301.24557495]
  [ 302.54476929  302.95553589  303.17333984  303.36541748  303.47024536
    303.50692749  303.46994019  303.40505981  303.24490356  303.14447021
    303.05990601  303.08932495  303.04507446  303.12121582  303.14147949
    302.91897583  302.61526489  302.62460327  302.4855957   302.41894531
    302.18325806  302.15148926  302.14376831  302.11798096  302.09646606
    302.34555054  302.24240112  302.26278687  301.79840088  301.67034912]
  [ 302.90713501  303.14627075  303.28775024  303.32659912  303.30874634
    303.26242065  303.27932739  303.4125061   303.33999634  303.21194458
    303.18118286  303.19500732  303.11932373  303.35769653  303.16323853
    303.29586792  302.87179565  303.19470215  303.12869263  302.65533447
    302.59960938  302.66656494  302.65930176  302.66360474  302.57284546
    302.80267334  302.574646    302.84631348  302.86053467  302.68551636]
  [ 303.1552124   303.28070068  303.38470459  303.34637451  303.29284668
    303.17584229  303.2628479   303.35516357  303.36187744  303.22402954
    303.18890381  303.21282959  303.33422852  303.22662354  303.19561768
    303.55960083  302.96395874  303.01663208  303.09936523  302.82299805
    302.85180664  303.01852417  303.0675354   303.00839233  303.39303589
    303.48834229  304.13513184  304.35443115  304.17980957  303.88613892]
  [ 303.21810913  303.29440308  303.43927002  303.35696411  302.94979858
    303.21707153  303.3515625   303.43624878  303.49508667  303.44784546
    303.50009155  303.68948364  303.65750122  302.45797729  302.87704468
    304.34466553  304.11914062  303.80419922  304.03930664  304.45651245
    304.63708496  304.15856934  304.13293457  304.67489624  305.29797363
    305.30133057  305.03018188  305.19552612  304.63967896  304.22897339]
  [ 302.78289795  303.08932495  303.35314941  303.355896    303.1385498
    303.31039429  303.6473999   303.87310791  303.91445923  303.99069214
    304.2359314   304.60028076  304.88790894  305.12167358  305.34094238
    305.12887573  304.54089355  304.68978882  305.07131958  305.78607178
    306.03768921  306.12301636  306.23526001  306.1395874   306.02932739
    305.65997314  305.65213013  305.50421143  304.83462524  303.75338745]
  [ 303.05950928  303.42544556  303.68148804  303.7532959   303.68453979
    303.66769409  303.9006958   304.22805786  304.31570435  304.49887085
    304.94952393  305.39978027  305.74468994  305.81283569  305.61184692
    304.9425354   304.51782227  304.03594971  304.07040405  305.29138184
    305.87908936  306.06167603  306.29257202  306.25619507  305.9352417
    305.91629028  305.92486572  305.39981079  304.66635132  304.3291626 ]],
              mask =
  False,
        fill_value = 1e+20))

In [9]:
from geonotebook.vis.ktile.utils import get_layer_vrt

In [11]:
print(get_layer_vrt(M.layers[0]))

<VRTDataset rasterXSize="1440" rasterYSize="720" subClass="VRTWarpedDataset">
  <SRS>GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]</SRS>
  <GeoTransform> -1.7999972534179688e+02,  2.4999967380111587e-01,  0.0000000000000000e+00,  9.0000000000000000e+01,  0.0000000000000000e+00, -2.4999984741212103e-01</GeoTransform>
  <VRTRasterBand dataType="Float32" band="1" subClass="VRTWarpedRasterBand">
    <NoDataValue>1.000000020040877e+20</NoDataValue>
  </VRTRasterBand>
  <BlockXSize>512</BlockXSize>
  <BlockYSize>128</BlockYSize>
  <GDALWarpOptions>
    <WarpMemoryLimit>6.71089e+07</WarpMemoryLimit>
    <ResampleAlg>NearestNeighbour</ResampleAlg>
    <WorkingDataType>Float32</WorkingDataType>
    <Option name="SOURCE_EXTRA">1000</Option>
    <Option name="INIT_DEST">NO_DATA</Option>
    <SourceDataset relativeToVRT="0">/data/kotfic/climate/tasmax_day_BCSD_rcp45_r1i1p1_ACCESS1-0_2100.nc</SourceDataset>
    <Transformer>
      <ApproxTransformer>
        <MaxError>0.125</MaxError>
        <BaseTransformer>
          <GenImgProjTransformer>
            <SrcGeoTransform>0,0.25,0,90,0,-0.25</SrcGeoTransform>
            <SrcInvGeoTransform>-0,4,0,360,0,-4</SrcInvGeoTransform>
            <DstGeoTransform>-179.999725341796875,0.249999673801115874,0,90,0,-0.249999847412121029</DstGeoTransform>
            <DstInvGeoTransform>719.999840819766064,4.00000521918895569,0,360.000219726679802,0,-4.00000244140755346</DstInvGeoTransform>
            <ReprojectTransformer>
              <ReprojectionTransformer>
                <SourceSRS>GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",180,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"],EXTENSION["CENTER_LONG",180]]</SourceSRS>
                <TargetSRS>GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]</TargetSRS>
              </ReprojectionTransformer>
            </ReprojectTransformer>
          </GenImgProjTransformer>
        </BaseTransformer>
      </ApproxTransformer>
    </Transformer>
    <BandList>
      <BandMapping src="1" dst="1">
        <SrcNoDataReal>1.000000020040877e+20</SrcNoDataReal>
        <SrcNoDataImag>0</SrcNoDataImag>
        <DstNoDataReal>1.000000020040877e+20</DstNoDataReal>
        <DstNoDataImag>0</DstNoDataImag>
      </BandMapping>
    </BandList>
  </GDALWarpOptions>
</VRTDataset>